In [1]:
import numpy as np

In [63]:
#Ejercicio 1
#Dado el arreglo a = np.array([1, 2, 3, 4]), determina si ninguno de los elementos es cero.
a = np.array([1, 2, 3, 4])

resultado = np.all(a != 0)
print(resultado)

True


In [64]:
#Ejercicio 2 
#Dado el arreglo a = np.array([0, 0, 2, 0]), determina si contiene algún elemento que no sea cero.
a = np.array([0, 0, 2, 0])

resultado = np.any(a != 0)
print(resultado)

True


In [65]:
#Ejercicio 3
#Analiza el arreglo a = np.array([1, 2, np.nan, np.inf]) y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
a = np.array([1, 2, np.nan, np.inf])
resultado = np.any(np.isnan(a) | np.isinf(a))
print(resultado)

True


In [66]:
#Ejercicio 4
#Dado el arreglo a = np.array([1, 2, np.inf]), determina si contiene valores infinitos.
a = np.array([1, 2, np.inf])
resultado = np.any(np.isinf(a))
print(resultado)

True


In [67]:
#Ejercicio 5
#Dado el arreglo a = np.array([1, np.nan, 3]), determina si contiene valores NaN.
a = np.array([1, np.nan, 3])
resultado = np.any(np.isnan(a))
print(resultado)

True


In [68]:
#Ejercicio 6
#Dados los arreglos a = np.array([1, 3, 5]) y b = np.array([2, 3, 4]), realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
mayor = a > b
mayorigual = a >= b
menor = a < b
menorigual = a <= b
print("a > b:", mayor)
print("a >= b:", mayorigual)
print("a < b:", menor)
print("a <= b:", menor)

a > b: [False False  True]
a >= b: [False  True  True]
a < b: [ True False False]
a <= b: [ True False False]


In [69]:
#Ejercicio 7
#Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
a = np.array([1, 7, 13, 105])
memoria = a.nbytes
print("Bytes utilizados: ", memoria)

Bytes utilizados:  32


In [70]:
#Ejercicio 8
#Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.

#Manual
a = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
b = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
c = np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#Automático
a1 = np.zeros(10)
b1 = np.ones(10)
c1 = np.full(10, 5)
print(a1)
print(b1)
print(c1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [71]:
#Ejercicio 9
#Crea un arreglo que contenga todos los números enteros entre 30 y 70.
a = np.arange(30, 70)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [72]:
 #Ejercicio 10
#Crea un arreglo que contenga los números pares entre 30 y 70.
a = np.arange(30, 70, 2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [73]:
#Ejercicio 11
#Crea una matriz identidad de 3x3.
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
#Ejercicio 12
#Genera un número aleatorio entre 0 y 1.
num = np.random.rand()
print(num)

0.7596408327701287


In [75]:
#Ejercico 13
#Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
a = np.random.rand(15)
print(a)

[0.83172622 0.13637755 0.04556846 0.11387374 0.64347486 0.6364181
 0.56172009 0.82828715 0.35054415 0.61062429 0.23338794 0.90354088
 0.64142415 0.81500117 0.40226942]


In [76]:
#Ejercicio 14
#Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
a = np.arange(16, 54)
print(a)

b = np.arange(15, 55)
print(b[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [77]:
#Ejercicio 15
#Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
a = np.linspace(5, 50, 10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [78]:
#Ejercicio 16
#Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
a = np.arange(0, 20)
a[(a >= 9) & (a <= 15)]*= -1
print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [79]:
#Ejercicio 17
#Convierte el arreglo a = np.array([1, 2, 3]) a una lista de Python.
a = np.array([1, 2, 3])
l = a.tolist()
print(l)

[1, 2, 3]


In [80]:
#Ejercicio 18
#Convierte la lista l = [1, 2, 3] a un arreglo de Numpy.
l = a.tolist()
a = np.array(l)
print(a)

[1 2 3]


In [81]:
#Ejercicio 19
#Dada la matriz m = np.array([[1, 2], [3, 4]]), verifica qué números son pares y almacena los resultados en otra matriz.
m = np.array([[1, 2], [3, 4]])
par = (m % 2 == 0)
print(par)

[[False  True]
 [False  True]]


In [85]:
#Ejercicio 20
#Dado el arreglo m = np.array([[1, 2, 3], [4, 5, 6]]), encuentra el número de filas y columnas de la matriz.
m = np.array([[1, 2, 3], [4, 5, 6]])
f, c = m.shape
print(m)
print("Número de filas: ", f)
print("Número de columnas: ", c)

[[1 2 3]
 [4 5 6]]
Número de filas:  2
Número de columnas:  3
